---
- name: Simple rulebook example that prints the payload received
  hosts: localhost
  sources:
    - name: dynatrace_events
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5005
  rules:
    - name: Remediate failing Kubernetes pod and close ServiceNow incident
      condition: >
        eventpayload.eventType == "K8S_POD_REMEDIATION"
      action:
        debug: